# Generated by Django 2.2 on 2019-04-28 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceJourney',
            new_name='JourneyPlace',
        ),
        migrations.AddField(
            model_name='voucher',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='journey.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserVoucher',
        ),
    ]
