# Generated by Django 2.2 on 2019-04-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_auto_20190428_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyplace',
            name='visited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
