# Generated by Django 2.2 on 2019-04-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_journeyplace_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjourney',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='userjourney',
            name='user',
        ),
        migrations.AddField(
            model_name='journey',
            name='place',
            field=models.ManyToManyField(to='journey.Place'),
        ),
        migrations.AddField(
            model_name='user',
            name='journey',
            field=models.ManyToManyField(to='journey.Journey'),
        ),
        migrations.DeleteModel(
            name='JourneyPlace',
        ),
        migrations.DeleteModel(
            name='UserJourney',
        ),
    ]
