# Generated by Django 2.2 on 2019-04-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0004_auto_20190428_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
