# Generated by Django 2.2 on 2019-04-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_auto_20190428_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='code',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
