# Generated by Django 2.2 on 2019-04-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='journey.User'),
        ),
    ]
