# Generated by Django 2.2 on 2019-04-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0008_auto_20190428_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='category',
            field=models.CharField(choices=[('Bronze', 0), ('Silver', 1), ('Gold', 2), ('Platinum', 3)], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
