# Generated by Django 2.2 on 2019-04-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0011_voucher_is_halal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='is_halal',
        ),
        migrations.AddField(
            model_name='place',
            name='is_halal',
            field=models.BooleanField(default=True),
        ),
    ]
