# Generated by Django 2.2 on 2019-04-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0015_auto_20190428_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='reward_category',
            field=models.CharField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold'), (3, 'Platinum')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
