# Generated by Django 2.2 on 2019-04-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0016_journey_reward_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='reward_category',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=10),
        ),
    ]
